/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package première.pkginterface.graphique_buatois;

/**
 *
 * @author User
 */
public class FenêtrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenêtrePrincipale
     */
    public FenêtrePrincipale() {
        initComponents();
        System.out.println("fenêtre crée");
        msgBienvenue.setText("bonjour le monde");
        jLabel_resultat.setVisible(false);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgBienvenue = new javax.swing.JLabel();
        msgFin = new javax.swing.JLabel();
        Bouton_valider = new javax.swing.JButton();
        ZoneNom = new javax.swing.JTextField();
        jLabel_resultat = new javax.swing.JLabel();
        demandePrenom = new javax.swing.JLabel();
        EntrerSalaire = new javax.swing.JLabel();
        AugmenterSalaire = new javax.swing.JButton();
        ZoneSalaire = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msgBienvenue.setText("arthurcdur");

        msgFin.setText("Good Bye");

        Bouton_valider.setText("Change all");
        Bouton_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_validerActionPerformed(evt);
            }
        });

        jLabel_resultat.setText("Resultat");

        demandePrenom.setText("EntrezVotrePrenom");

        EntrerSalaire.setText("Entrez votre salaire");

        AugmenterSalaire.setText("Augmenter salaire");
        AugmenterSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugmenterSalaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(msgFin)
                            .addComponent(msgBienvenue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Bouton_valider)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EntrerSalaire)
                            .addComponent(jLabel_resultat))
                        .addGap(18, 18, 18)
                        .addComponent(ZoneSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(AugmenterSalaire))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(demandePrenom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZoneNom, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(msgBienvenue)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZoneNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(demandePrenom))
                .addGap(42, 42, 42)
                .addComponent(Bouton_valider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel_resultat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EntrerSalaire)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AugmenterSalaire)
                        .addComponent(ZoneSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(msgFin)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_validerActionPerformed
        // TODO add your handling code here:
        msgFin.setText("au revoir en français!");
        String a = ZoneNom.getText();
        jLabel_resultat.setText("Bonjour "+a);
        jLabel_resultat.setVisible(true);
    }//GEN-LAST:event_Bouton_validerActionPerformed

    private void AugmenterSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugmenterSalaireActionPerformed
        // TODO add your handling code here:
        String salaire = ZoneSalaire.getText();
        int salaire_entier = Integer.parseInt(salaire);
        salaire_entier++; // j'augmente de 1
        ZoneSalaire.setText(salaire_entier + "");
    }//GEN-LAST:event_AugmenterSalaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenêtrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AugmenterSalaire;
    private javax.swing.JButton Bouton_valider;
    private javax.swing.JLabel EntrerSalaire;
    private javax.swing.JTextField ZoneNom;
    private javax.swing.JTextField ZoneSalaire;
    private javax.swing.JLabel demandePrenom;
    private javax.swing.JLabel jLabel_resultat;
    private javax.swing.JLabel msgBienvenue;
    private javax.swing.JLabel msgFin;
    // End of variables declaration//GEN-END:variables
}
