/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkginterface.graphique.à.arthur;

/**
 *
 * @author User
 */
public class Fenêtre_Principale extends javax.swing.JFrame {

    /**
     * Creates new form Fenêtre_Principale
     */
    public Fenêtre_Principale() {
        initComponents();
        reponse.setVisible(false);
        BonneReponse.setVisible(false);
        MauvaiseReponse.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consigne = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        reponse = new javax.swing.JLabel();
        reponse1 = new javax.swing.JButton();
        reponse2 = new javax.swing.JButton();
        BonneReponse = new javax.swing.JLabel();
        MauvaiseReponse = new javax.swing.JLabel();
        Titre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consigne.setText("Sélectionnez la bonne réponse: ");
        getContentPane().add(consigne, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 73, -1, -1));

        question.setText("Combien de bosses a le dromadaire ?");
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        reponse.setText("Le dromadaire a une seule bosse.");
        getContentPane().add(reponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        reponse1.setText("1 bosse");
        reponse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponse1ActionPerformed(evt);
            }
        });
        getContentPane().add(reponse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        reponse2.setText("2 bosses");
        reponse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponse2ActionPerformed(evt);
            }
        });
        getContentPane().add(reponse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        BonneReponse.setText("Bonne réponse!");
        getContentPane().add(BonneReponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        MauvaiseReponse.setText("Mauvaise réponse!");
        getContentPane().add(MauvaiseReponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        Titre.setText("QUIZZ");
        getContentPane().add(Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reponse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponse1ActionPerformed
        // TODO add your handling code here:
        BonneReponse.setVisible(true);
        MauvaiseReponse.setVisible(false);
        reponse.setVisible(true);
    }//GEN-LAST:event_reponse1ActionPerformed

    private void reponse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponse2ActionPerformed
        // TODO add your handling code here:
        MauvaiseReponse.setVisible(true);
        BonneReponse.setVisible(false);
        reponse.setVisible(true);
    }//GEN-LAST:event_reponse2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenêtre_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BonneReponse;
    private javax.swing.JLabel MauvaiseReponse;
    private javax.swing.JLabel Titre;
    private javax.swing.JLabel consigne;
    private javax.swing.JLabel question;
    private javax.swing.JLabel reponse;
    private javax.swing.JButton reponse1;
    private javax.swing.JButton reponse2;
    // End of variables declaration//GEN-END:variables
}
