/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lights_off_blanc_buatois;

/**
 *
 * @author User
 */
public class fennetredeJeu extends javax.swing.JFrame {

    Joueur JoueurCourant;
    GrilleDeJeu Grille;
    /**
     * Creates new form fennetredeJeu
     */
    public fennetredeJeu() {
        initComponents();
        panneau_info.setVisible(false);
        
        for (int i=4; i>=0; i--){
            for (int j=0; i>=5; i++){
                cellule_graphique cellgraph = new cellulegraphique(GrilleDeJeu.Grille[i][j]);
                panneau_grille.add(cellgraph);
            }
        }
        // crer une boucle pour cré les boutons dans le panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panneau_grille = new javax.swing.JPanel();
        panneau_info = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_joueur = new javax.swing.JTextField();
        boutondemarrerpartie = new javax.swing.JButton();
        Règles = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        bouton_règles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Light Off");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 6, 90, 40));

        panneau_grille.setBackground(new java.awt.Color(153, 204, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 480, 480));

        panneau_info.setBackground(new java.awt.Color(51, 153, 255));
        panneau_info.setForeground(new java.awt.Color(51, 153, 255));
        panneau_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nom joueur");
        panneau_info.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setText("Partie");
        panneau_info.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        nom_joueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueurActionPerformed(evt);
            }
        });
        panneau_info.add(nom_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 70, -1));

        boutondemarrerpartie.setText("Démarrer partie");
        boutondemarrerpartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutondemarrerpartieActionPerformed(evt);
            }
        });
        panneau_info.add(boutondemarrerpartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        getContentPane().add(panneau_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 190, 150));

        Règles.setBackground(new java.awt.Color(0, 153, 255));
        Règles.setForeground(new java.awt.Color(0, 102, 255));
        Règles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Infos jeu");
        Règles.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);

        Règles.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 130));

        bouton_règles.setText("Règles");
        Règles.add(bouton_règles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        getContentPane().add(Règles, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 190, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueurActionPerformed

    private void boutondemarrerpartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutondemarrerpartieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutondemarrerpartieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fennetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fennetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fennetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fennetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fennetredeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Règles;
    private javax.swing.JButton bouton_règles;
    private javax.swing.JButton boutondemarrerpartie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField nom_joueur;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info;
    // End of variables declaration//GEN-END:variables
}
